services:
    api:
      container_name: backend_eco_api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"

    dashboard:
      container_name: frontend_eco_dash
      build:
        context: .
        dockerfile: dashboard/Dockerfile
      ports:
        - "8501:8501"
      environment:
        API_URL: http://api:8000
      depends_on:
        - api